name: brew bottle

on:
  workflow_call:
    inputs:
      formula:
        type: string
        default: viam
        description: which formula to bottle
  workflow_dispatch:
    inputs:
      formula:
        type: string
        default: viam
        description: which formula to bottle

jobs:
  bottle:
    concurrency:
      # these make git commits and will fail if they overlap at all
      group: bottle-mutex
    strategy:
      matrix:
        # macos-14 is apple silicon
        runs-on: [ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - uses: actions/checkout@v4

      - name: git setup
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "actions bot"
          git config push.autoSetupRemote true

      - name: build and push bottle
        env:
            HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
            HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
            # if you don't override root-url it will upload to / download from the wrong place
            ROOT_URL: https://ghcr.io/v2/${{ github.repository }}
        run: |
          brew tap viamrobotics/brews
          brew install --build-bottle ${{ inputs.formula }}
          brew bottle --json --root-url $ROOT_URL ${{ inputs.formula }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runs-on }}
          if-no-files-found: error
          path: '*.bottle.*'

  upload:
    needs: bottle
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: Homebrew/actions/setup-homebrew@master
    - uses: actions/checkout@v4

    - name: download artifacts
      run: |
        brew tap viamrobotics/brews
        ls
        gh run download ${{ github.run_id }}
        ls
        ls macos-14
        mv */*.bottle.* .
        ls

    - name: push changes
      if: false # tmp disable
      run: |
        cd $(brew --prefix)/Homebrew/Library/Taps/${{ github.repository }}
        # note: the tap is on the current branch rather than main. not sure why, seems sensitive to whether we run actions/checkout.
        git log | head
        git status
        git push
