name: brew bottle

on:
  workflow_call:
    inputs:
      formula:
        type: string
        default: viam
        description: which formula to bottle
    secrets:
      GIT_ACCESS_TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      formula:
        type: string
        default: viam
        description: which formula to bottle

env:
  # if you don't override root-url it will upload to / download from the wrong place
  ROOT_URL: https://ghcr.io/v2/${{ github.repository }}

jobs:
  bottle:
    strategy:
      matrix:
        runs-on: [ubuntu-22.04, macos-14, macos-15]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
        with:
          stable: true
      - uses: actions/checkout@v4
      - name: pull
        run: |
          # see note below on why we need to pull
          git pull

      - name: build bottle
        run: |
          # without this force-install, the pkgconf dep of viam-server conflicts with the one github preinstalls on runners, and the build fails
          brew install --force --overwrite pkg-config

          brew tap viamrobotics/brews
          # note: this fails on the nlopt dep to viam-server when viam-server already exists as bottle in the formula file.
          # weird edge case. recovery is to remove the bottle stanza and delete the uploaded package, then rerun.
          brew install --only-dependencies ${{ inputs.formula }}
          brew install --build-bottle ${{ inputs.formula }}
          brew bottle --json --root-url $ROOT_URL ${{ inputs.formula }}
      
      - name: Generate UUID
        id: uuid_step
        run: echo "::set-output name=uuid::$(uuidgen)"
  
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runs-on }}-${{ steps.uuid_step.outputs.uuid }}
          if-no-files-found: error
          path: '*.bottle.*'
