name: brew pr-pull

on:
  workflow_dispatch:
  # pull_request_target:
  #   types:
  #     - labeled

jobs:
  pr-pull:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - uses: actions/checkout@v4

      - name: become actions bot
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "actions bot"

      - name: try bottling
        env:
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
        run: |
          # this could be ./Formula/viam.rb but that gives you 3-6 warnings at various points
          # brew install --build-bottle viamrobotics/brews/viam
          # brew bottle --json viam
          # brew pr-upload # --dry-run
          brew test-bot viamrobotics/brews/viam
 
      # - name: Pull bottles
      #   env:
      #     HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
      #     HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
      #     HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
      #     PULL_REQUEST: ${{ github.event.pull_request.number }}
      #   run: brew pr-pull --debug --tap="$GITHUB_REPOSITORY" "$PULL_REQUEST"

      # - name: Push commits
      #   uses: Homebrew/actions/git-try-push@master
      #   with:
      #     token: ${{ github.token }}
      #     branch: main

      # - name: Delete branch
      #   if: github.event.pull_request.head.repo.fork == false
      #   env:
      #     BRANCH: ${{ github.event.pull_request.head.ref }}
      #   run: git push --delete origin "$BRANCH"
