name: brew pr-pull

on:
  workflow_dispatch:
    inputs:
      runner:
        default: ubuntu-22.04
        description: passed down to runs-on

jobs:
  pr-pull:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - uses: actions/checkout@v4

      - name: git setup
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "actions bot"
          git config push.autoSetupRemote true

      - name: build and push bottle
        env:
            HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
            HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
        run: |
          brew tap viamrobotics/brews
          brew install --build-bottle viam
          brew bottle --json viam
          brew pr-upload --root-url https://ghcr.io/v2/${{ github.repository }}

      - name: push changes
        run: |          
          cd $(brew --prefix)/Homebrew/Library/Taps/${{ github.repository }}
          # note: the tap is on the current branch rather than main. not sure why, seems sensitive to whether we run actions/checkout.
          # this will be run from main so this isn't a deal-breaker.
          git log | head
          git status
          git push
