# This should mostly mirror the bottom of the bump-versions.yml workflow.
# We use this to run just the build-and-upload steps for bottling.
# This workflow is useful for testing changes to bottling + also to rerun if something has gone wrong.
# Note: you may sometimes need to manually clean up a bad run by deleting the extra packages at:
# https://github.com/orgs/viamrobotics/packages?repo_name=homebrew-brews
# And by removing the bottle stanza in the formulas.

on:
  workflow_dispatch:

jobs:
  bottle-viam:
    uses: ./.github/workflows/bottle.yml
    with:
      formula: viam
    secrets:
      GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

  bottle-viam-server:
    uses: ./.github/workflows/bottle.yml
    with:
      formula: viam-server
    secrets:
      GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

  upload:
    needs: [bottle-viam, bottle-viam-server]
    uses: ./.github/workflows/upload.yml
    secrets:
      GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
