name: brew upload

on:
    workflow_call:
        secrets:
            GIT_ACCESS_TOKEN:
                required: true
    workflow_dispatch:

env:
    # if you don't override root-url it will upload to / download from the wrong place
    ROOT_URL: https://ghcr.io/v2/${{ github.repository }}

jobs:
    upload:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          packages: write
        steps:
        - uses: Homebrew/actions/setup-homebrew@master
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.GIT_ACCESS_TOKEN }}
    
        - name: git setup
          run: |
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "actions bot"
            git config push.autoSetupRemote true
            git branch
            # why pull: for the case where we are bottling two formulae, formula 1 will push a new commit.
            # Then formula 2's bottle job will check out the original commit, try to push, and collid with
            # formula 1's commit.
            git pull
    
        - name: download artifacts
          env:
            GH_TOKEN: ${{ github.token }}
          run: |
            brew tap viamrobotics/brews
            gh run download ${{ github.run_id }}
            mv */*.bottle.* .
            ls
    
        - name: upload
          env:
            HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
            HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          run: brew pr-upload --root-url $ROOT_URL
    
        - name: push changes
          run: |
            cd $(brew --prefix)/Homebrew/Library/Taps/${{ github.repository }}
            # note: the tap is on the current branch rather than main. not sure why, seems sensitive to whether we run actions/checkout.
            git log | head
            git status
            git push